"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MnemonicZH_HK = exports.MnemonicZH_CN = exports.MnemonicPT = exports.MnemonicKO = exports.MnemonicJA = exports.MnemonicIT = exports.MnemonicFR = exports.MnemonicES = exports.MnemonicEN = exports.MnemonicCZ = exports.Mnemonic = void 0;
var mnemonic_class_1 = require("./mnemonic.class");
Object.defineProperty(exports, "Mnemonic", { enumerable: true, get: function () { return mnemonic_class_1.Mnemonic; } });
var cz_class_1 = require("./languages/cz.class");
Object.defineProperty(exports, "MnemonicCZ", { enumerable: true, get: function () { return cz_class_1.MnemonicCZ; } });
var en_class_1 = require("./languages/en.class");
Object.defineProperty(exports, "MnemonicEN", { enumerable: true, get: function () { return en_class_1.MnemonicEN; } });
var es_class_1 = require("./languages/es.class");
Object.defineProperty(exports, "MnemonicES", { enumerable: true, get: function () { return es_class_1.MnemonicES; } });
var fr_class_1 = require("./languages/fr.class");
Object.defineProperty(exports, "MnemonicFR", { enumerable: true, get: function () { return fr_class_1.MnemonicFR; } });
var it_class_1 = require("./languages/it.class");
Object.defineProperty(exports, "MnemonicIT", { enumerable: true, get: function () { return it_class_1.MnemonicIT; } });
var ja_class_1 = require("./languages/ja.class");
Object.defineProperty(exports, "MnemonicJA", { enumerable: true, get: function () { return ja_class_1.MnemonicJA; } });
var ko_class_1 = require("./languages/ko.class");
Object.defineProperty(exports, "MnemonicKO", { enumerable: true, get: function () { return ko_class_1.MnemonicKO; } });
var pt_class_1 = require("./languages/pt.class");
Object.defineProperty(exports, "MnemonicPT", { enumerable: true, get: function () { return pt_class_1.MnemonicPT; } });
var zh_cn_class_1 = require("./languages/zh-cn.class");
Object.defineProperty(exports, "MnemonicZH_CN", { enumerable: true, get: function () { return zh_cn_class_1.MnemonicZH_CN; } });
var zh_hk_class_1 = require("./languages/zh-hk.class");
Object.defineProperty(exports, "MnemonicZH_HK", { enumerable: true, get: function () { return zh_hk_class_1.MnemonicZH_HK; } });
